FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.24-openshift-4.21 AS builder
WORKDIR /go/src/github.com/openshift/volume-data-source-validator
COPY . .
RUN make build

FROM registry.ci.openshift.org/ocp/4.21:base-rhel9
COPY --from=builder /go/src/github.com/openshift/volume-data-source-validator/bin/volume-data-source-validator /usr/bin/
ENTRYPOINT ["/usr/bin/volume-data-source-validator"]